### PR TITLE
Riot Games Plugin

### PR DESCRIPTION
**Pull request by ZenMaxe**
Added New Plugin

### CODE REVIEW

**Comment by tekgator** [comment]
@ZenMaxe sorry for the late response, I'm currently moving intercontinental, so haven't had a chance yet to look at everything in detail. I'll have some time the upcoming weekend and will merge.

**Comment by tekgator** [comment]
@ZenMaxe: Could you adjust the README's for the main project and add a README for the plugin?

**Comment by ZenMaxe** [comment]
> @ZenMaxe: Could you adjust the README's for the main project and add a README for the plugin?

Sure

**Comment by ZenMaxe** [comment]
@tekgator i think it's ready now!

**Review by tekgator — APPROVED** [review]
Slight issue on the Plugin ReadMe still pointing to another plugin, otherwise perfect.

**Comment by tekgator** [comment]
@ZenMaxe : the plugin has now been incorporated. Nuget 1.4.0 has now been released. Thanks for your effort. 👍

**Comment by ZenMaxe** [comment]
> Slight issue on the Plugin ReadMe still pointing to another plugin, otherwise perfect.

Sorry, My Bad!

**Pull request merged**
